export const dishes = [
    {
        id: 1,
        name: "Vegan Buddha Bowl",
        description:
            "A healthy bowl of quinoa, chickpeas, avocado, and mixed vegetables.",
        price: 12.99,
        image: "https://biancazapatka.com/wp-content/uploads/2021/07/buddha-bowl-hummus-720x1008.jpg",
        category: ["Vegan", "Main Dish", "Healthy"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 2,
        name: "Classic Cheeseburger",
        description:
            "Juicy beef patty with cheddar cheese, lettuce, tomato, and pickles on a sesame bun.",
        price: 10.99,
        image: "https://www.oliveandmango.com/images/uploads/2021_06_21_classic_grilled_cheeseburger_1.jpg",
        category: ["Comfort Food", "Main Dish", "Fast Food"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 3,
        name: "Margherita Pizza",
        description:
            "Traditional Italian pizza with fresh tomatoes, mozzarella, and basil.",
        price: 14.99,
        image: "https://preppykitchen.com/wp-content/uploads/2024/01/Margherita-Pizza-Recipe-Card.jpg",
        category: ["Comfort Food", "Main Dish", "Traditional"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 4,
        name: "Tofu Stir-fry",
        description:
            "Stir-fried tofu with mixed vegetables and a savory soy sauce glaze.",
        price: 11.99,
        image: "https://veganhuggs.com/wp-content/uploads/2020/10/Tofu-Stir-Fry-Square.jpg",
        category: ["Vegan", "Main Dish", "Healthy"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 5,
        name: "Caesar Salad",
        description:
            "Crisp romaine lettuce, parmesan cheese, croutons, and Caesar dressing.",
        price: 8.99,
        image: "https://www.joyfulhealthyeats.com/wp-content/uploads/2022/04/Classic-Caesar-Salad-with-Homemade-Croutons-web-4.jpg",
        category: ["Salads", "Appetizer", "Healthy"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 6,
        name: "Spaghetti Carbonara",
        description:
            "Classic Italian pasta with creamy egg sauce, pancetta, and parmesan.",
        price: 13.99,
        image: "https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-square640-v2.jpg",
        category: ["Comfort Food", "Main Dish", "Traditional"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 7,
        name: "Grilled Chicken Sandwich",
        description:
            "Grilled chicken breast with lettuce, tomato, and mayo on a whole-grain bun.",
        price: 9.99,
        image: "https://easychickenrecipes.com/wp-content/uploads/2023/06/grilled-chicken-sandwich-1-of-6-edited.jpg",
        category: ["Comfort Food", "Main Dish", "Healthy"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 8,
        name: "Quinoa Salad",
        description:
            "Fresh quinoa with cucumbers, cherry tomatoes, red onion, and feta cheese.",
        price: 10.49,
        image: "https://cdn.loveandlemons.com/wp-content/uploads/2020/08/quinoa-salad.jpg",
        category: ["Salads", "Side Dish", "Healthy"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 9,
        name: "Vegan Tacos",
        description:
            "Soft corn tortillas filled with black beans, avocado, and pico de gallo.",
        price: 11.49,
        image: "https://www.twospoons.ca/wp-content/uploads/2020/07/best-vegan-taco-recipe-easy-how-to-make-vegan-tacos-twospoons-5.jpg",
        category: ["Vegan", "Main Dish", "Comfort Food"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 10,
        name: "BBQ Ribs",
        description:
            "Slow-cooked pork ribs smothered in BBQ sauce, served with coleslaw.",
        price: 16.99,
        image: "https://cafedelites.com/wp-content/uploads/2018/06/Oven-Pork-Ribs-IMAGE-3.jpg",
        category: ["Comfort Food", "Main Dish", "Traditional"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 11,
        name: "Vegan Burger",
        description:
            "Plant-based patty with lettuce, tomato, onion, and vegan mayo on a gluten-free bun.",
        price: 12.49,
        image: "https://www.thespruceeats.com/thmb/e-lll-PpJ5F-MF4C57LYag3IAB8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-vegan-black-bean-veggie-burgers-3377008-hero-05-f7c0f0d9865e48b6be52a4c76ee22438.jpg",
        category: ["Vegan", "Main Dish", "Fast Food"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 12,
        name: "Greek Salad",
        description:
            "Crisp lettuce, feta cheese, olives, cucumber, and red onion with a tangy vinaigrette.",
        price: 9.49,
        image: "https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2018/08/Greek-Salad-6-1.jpg",
        category: ["Salads", "Appetizer", "Traditional"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 13,
        name: "Buckwheat",
        description: "Traditional Ukrainian buckwheat porridge.",
        price: 5.99,
        image: "https://images.ctfassets.net/16o89hgrwn8f/4QlY6z7mhg4uDppJWf3gHT/0a851f043a28f7b4682acc271fd3cfeb/buckwheat_kasha_2_2022-0041_2460x1270_72.jpg?w=1900&h=1000&fm=jpg&q=50&fl=progressive&fit=fill&f=center",
        category: ["Traditional", "Main Dish", "Side Dish"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 14,
        name: "Pilaf",
        description: "Hearty dish made of rice, meat, and spices.",
        price: 12.99,
        image: "https://www.betterthanbouillon.com/wp-content/uploads/2020/11/One-Pan-Chicken-and-Rice-Pilaf-045.jpg",
        category: ["Main Dish", "Traditional"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 15,
        name: "Borscht",
        description: "Ukrainian red beet soup with cabbage and meat.",
        price: 7.99,
        image: "https://natashaskitchen.com/wp-content/uploads/2018/10/Borscht-Recipe-2.jpg",
        category: ["Soup", "Traditional", "Main Dish"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 16,
        name: "Dumplings with Potatoes",
        description: "Dumplings stuffed with tender mashed potatoes.",
        price: 8.99,
        image: "https://www.thespruceeats.com/thmb/eWsPTSffvihB-Uct_Wa6BNWLfnE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bavarian-potato-dumplings-1447183-hero-03-19edf047cc984e7d83d49e665e8d5746.jpg",
        category: ["Traditional", "Main Dish", "Comfort Food"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
    {
        id: 17,
        name: "Samsa",
        description: "Fried pastry filled with meat or vegetables.",
        price: 6.99,
        image: "https://swagataghosh.com/wp-content/uploads/2020/05/samsa1.jpg",
        category: ["Traditional", "Appetizer"],
        basketIcon: "/icons/basket-svgrepo-com.svg",
    },
];
